trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    pip install wheel
    pip install azure-storage-common azure-storage-blob azure-storage-file-share azure-storage-file-datalake azure-storage-queue azure-cosmosdb-table
  displayName: Install Python Packages

- script: |
    ./cleaner.py "$(storage_account1)"
    ./cleaner.py "$(storage_account2)"
    ./cleaner.py "$(storage_account3)"
    ./cleaner.py "$(storage_account4)"
  displayName: Run Cleaner
